# Generated by Django 4.0.6 on 2022-08-12 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_article_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='photo',
        ),
    ]
